version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: payment-gateway-postgres
    environment:
      POSTGRES_DB: paymentgatewaydb
      POSTGRES_USER: dinesh
      POSTGRES_PASSWORD: dinesh@2024
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
